### ISSUE TITLE
Making properties visible in diagram

### ISSUE THREAD

**Issue by MatheusPinto** [Modelio-R-D/MARTEDesigner#1]
I opened a topic in Modelio about the properties of MARTE: https://www.modelio.org/forum/13-modules/4896-how-to-edit-stereotypes-of-a-module.html#6535

From there, it turned out that MARTE stereotypes are not visible in the diagram. Is there a specific reason for this? Is it possible to change the module to make it visible?

**Comment by etiennebrosse** [comment]
Fixed in MARTE 5.4.01
